### ISSUE TITLE
Tailwind and Vue

### ISSUE THREAD

**Issue by domthomas-dev** [michaeldyrynda/laravel-preset-tailwind#100]
Hi, thanks for this packages.

Do you think to do a version like `ui vue`, but with tailwind and not bootstrap  ?

**Comment by eugenefvdm** [comment]
The documentation for this repo the under section **b. For Presets with Authentication** specifically has these instructions:

> Use `php artisan ui tailwindcss --auth` for the basic preset, auth route entry, and Tailwind CSS auth views in one go

Then if you head over to https://github.com/laravel/ui there is another item in bold:

**We are not accepting new presets.**

So:

1. You can use this package to do auth scaffolding.
2. At this point, and maybe for the foreseeable future, there won't be official auth scaffolding with the official Laravel UI package.

My guess is that Tailwind is too new and maybe too opinionated to make the cut (for now).

**Comment by michaeldyrynda** [comment]
These repos are maintained independently - and unofficially - of `laravel/ui`.

That said, I don't think we need to add Vue to the Tailwind preset.
