### ISSUE TITLE
leading-none on the body?

### ISSUE THREAD

**Issue by royduin** [michaeldyrynda/laravel-preset-tailwind#103]
Why is there a `leading-none` on the body? You can't just copy and paste the examples from Tailwind CSS or Tailwind UI because of it, they look different.

**Comment by michaeldyrynda** [comment]
This is just a preset to get you up and running in Laravel quickly, without having to configure all the build steps. 

If you need to change something once you’ve got the scaffolding setup, you’re free to do so in your app. 

I’d hazard a guess that if you’re using Tailwind UI, you’re not using much of the boilerplate included with this preset anyway.
