### ISSUE TITLE
ERROR NPM

### ISSUE THREAD

**Issue by Davides98** [michaeldyrynda/laravel-preset-tailwind#110]
I follow these commands:

composer require laravel-frontend-presets/tailwindcss --dev
php artisan ui tailwindcss --auth
npm install && npm run dev

but it isn't work
it generate this error

The Mix manifest does not exist. (View: C:\xampp\htdocs\site\resources\views\welcome.blade.php)

How fix it?

**Comment by Jevonne876** [comment]
I am getting the same error as well

**Comment by michaeldyrynda** [comment]
I'm not able to reproduce this (on a Mac). The mix manifest error indicates that the `npm run dev` step failed to complete properly. Did you get any errors from npm?

**Comment by Houbsi** [comment]
Hi @michaeldyrynda i just have a fresh install of laravel with the preset and got this:

`14% building 36/37 modules 1 active ...er/src/index.js??postcss0!/home/vagrant/code/townhouse/resources/css/app.cssnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-08-16T10_34_33_974Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-08-16T10_34_34_038Z-debug.log`
