### ISSUE TITLE
Adding Vue?

### ISSUE THREAD

**Issue by sajjadalis** [michaeldyrynda/laravel-preset-tailwind#111]
What is the best way to include vue with tailwind manually?

**Comment by innocenzi** [comment]
Hello,

To use Vue, after installing the preset, you will need to:

- Install the `vue` dependency
- Edit your `bootstrap.js` file to [register Vue and use your components](https://github.com/laravel/ui/tree/ec838c75ba1886d014c5465b1ecc79b2071f46c7/src/Presets/vue-stubs):


```js
window.Vue = require("vue");

Vue.component(
  "example-component",
  require("./components/ExampleComponent.vue").default
);

const app = new Vue({
  el: "#app"
});
```

- Create your Vue components (here, we register an `ExampleComponent.vue`)
- Use them in your Blade templates (eg. `<example-component></example-component>`)

https://vuejs.org/

**Comment by sajjadalis** [comment]
Thank you @innocenzi
