### ISSUE TITLE
npm run dev - ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Houbsi** [michaeldyrynda/laravel-preset-tailwind#112]
Hi all,

i just freshly installed laravel with this package and wanted to run `npm run dev` but unfortunatlly i get the below error message:

npm run dev

@ dev /home/vagrant/code/townhouse
npm run development

@ development /home/vagrant/code/townhouse
cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

14% building 36/37 modules 1 active ...er/src/index.js??postcss0!/home/vagrant/code/townhouse/resources/css/app.cssnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-08-16T10_34_33_974Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-08-16T10_34_34_038Z-debug.log

**Comment by michaeldyrynda** [comment]
Did you run `npm install` first?

**Comment by Houbsi** [comment]
Yeah of course. But i had to redo my whole system. now it works, couldn't figure out why.
