### ISSUE TITLE
Allow installation on Laravel8

### ISSUE THREAD

**Issue by ndeblauw** [michaeldyrynda/laravel-preset-tailwind#117]
I just wanted to show your package to a colleague on a fresh Laravel install and noticed that it isn't ^8.0 ready. If there isn't a blocking change (up to you to judge), I guess it's only a few minutes of work to update your composer.json. I'll show it on a Laravel7 install, so not urgent/important for me, but I just wanted to inform you. 

```
laravel-frontend-presets/tailwindcss 4.2.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev]
```

**Comment by adampatterson** [comment]
I have the same issue, I am upgrading a Laravel 7 app to 8 and the install fails.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel-frontend-presets/tailwindcss ^4.0 -> satisfiable by laravel-frontend-presets/tailwindcss[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.1.0, 4.2.0].
    - Can only install one of: laravel/framework[8.x-dev, 7.x-dev].
    - Can only install one of: laravel/framework[v8.0.0, 7.x-dev].
    - Can only install one of: laravel/framework[v8.0.1, 7.x-dev].
    - Can only install one of: laravel/framework[v8.0.2, 7.x-dev].
    - Conclusion: install laravel/framework 7.x-dev
    - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2].
```

**Comment by michaeldyrynda** [comment]
Supported in [4.3.0](https://github.com/laravel-frontend-presets/tailwindcss/releases/tag/4.3.0)

**Comment by adampatterson** [comment]
Thanks @michaeldyrynda!

**Comment by RichardDern** [comment]
According to [Laravel's upgrade guide](https://laravel.com/docs/8.x/upgrade#updating-dependencies), laravel/ui needs to be upgraded to 3.0, but it conflicts with this preset's dependencies.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/ui[3.x-dev, 2.x-dev].
    - Can only install one of: laravel/ui[v3.0.0, 2.x-dev].
    - laravel-frontend-presets/tailwindcss 4.3.0 requires laravel/ui ^2.0 -> satisfiable by laravel/ui[2.x-dev].
    - Installation request for laravel-frontend-presets/tailwindcss ^4.3 -> satisfiable by laravel-frontend-presets/tailwindcss[4.3.0].
    - Installation request for laravel/ui ^3.0 -> satisfiable by laravel/ui[3.x-dev, v3.0.0].
```

**Comment by ghost** [comment]
now can't install on laravel7 cause https://github.com/laravel-frontend-presets/tailwindcss/commit/ff2020fe586995728a82746ee531c8d15c9c7f74#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by michaeldyrynda** [comment]
You can use version ^4.2 and it ought to install to Laravel 7 just fine. 

There are differences between Laravel 7.x and 8.x that means ^4.3 won’t work in 7.x.
