### ISSUE TITLE
Unable to open Input file

### ISSUE THREAD

**Issue by Joaquim714** [michaeldyrynda/laravel-preset-tailwind#122]
this is the code i get when trying to open input file 

$ php artisan ui tailwindcss --auth
Could not open input file: artisan

How do you fix this issue?

**Comment by innocenzi** [comment]
Are you in a Laravel project? You need to create it before running that command. https://github.com/laravel-frontend-presets/tailwindcss#usage

**Comment by Joaquim714** [comment]
yes i am in one already
