### ISSUE TITLE
This preset changes the default colors of tailwindcss

### ISSUE THREAD

**Issue by Eboubaker** [michaeldyrynda/laravel-preset-tailwind#123]
after I nearly completed the design of the website, I installed this preset then I found that my website became ugly, I can't go to every blade file and change the colors, any fixes?

**Comment by michaeldyrynda** [comment]
Hey, two important things to note here:

1. I wouldn't add the preset to an existing project; it's used to scaffold out a new project
2. The preset uses the [`@tailwindcss/ui`](https://github.com/laravel-frontend-presets/tailwindcss/blob/main/src/TailwindCssPreset.php#L32) plugin, which [overrides the 1.x defaults](https://tailwindui.com/documentation#add-the-tailwindcss-ui-plugin) in preparation for the next major Tailwind version.

You can remove the plugin and recompile your assets.
