### ISSUE TITLE
Composer installation fails with latest Laravel 7 version

### ISSUE THREAD

**Issue by KimPrince** [michaeldyrynda/laravel-preset-tailwind#124]
Installed latest Laravel 7 with the following command:

`composer create-project --prefer-dist laravel/laravel:^7.0 blog`

Changed into the blog directory and ran:

`composer require laravel-frontend-presets/tailwindcss --dev`

Installation failed per the attached screenshot.  Composer lock file shows Laravel at 7.28.4

![Screen Shot 2020-10-14 at 3 36 32 pm](https://user-images.githubusercontent.com/1072441/95944209-6c6aed80-0e33-11eb-92d0-9f3b39a89bcd.png)

**Comment by KimPrince** [comment]
OK, I see now that you have changed your composer.json to require Laravel 8.  In this case it would probably be a good idea to change the heading in the read.me.

Secondly, I wonder if you would reconsider and support version 7?  It seems to me that there are plenty of users who want the familiar laravel/ui auth resources (e.g. routes, controllers), but would like to adopt tailwind.css

**Comment by michaeldyrynda** [comment]
You can use `^4.2`, which still works with Laravel 7.
