### ISSUE TITLE
Tailwind 2 Upgrade

### ISSUE THREAD

**Issue by abishekrsrikaanth** [michaeldyrynda/laravel-preset-tailwind#125]
Can you advice what needs to be done to upgrade to the latest @2 version of tailwind?

**Comment by michaeldyrynda** [comment]
Haven't looked, it just came out. The [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v2) would be a good place to start. 

A PR would be appreciated if you can get started on it ❤️

**Comment by mrailton** [comment]
Have looked into it, but seems that tailwind is gonna need [Laravel Mix](https://www.npmjs.com/package/laravel-mix) v6.0 which is still in beta at mo.

I've tested out the [changes here](https://dev.to/robertobutti/how-to-install-tailwind-css-2-with-laravel-8-4bom) and it seems to work fine, just means using beta software.

**Comment by MuhammedAO** [comment]
![Screenshot (110)](https://user-images.githubusercontent.com/52624960/103954208-03e69080-5144-11eb-9791-f6621f72df73.png)
I keep getting this error whenever i run the `npm run dev ` command to use the tailwind preset with auth in laravel 8. Any suggestions??
