### ISSUE TITLE
'mix' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by MuhammedAO** [michaeldyrynda/laravel-preset-tailwind#127]
![Screenshot (110)](https://user-images.githubusercontent.com/52624960/103954361-56c04800-5144-11eb-993b-444bbc124376.png)

I get this error whenever i run the `npm run dev`  in laravel 8. Any suggestion on what might the cause??

**Comment by royduin** [comment]
Probably the Laravel Mix update to version 6

**Comment by royduin** [comment]
Have a look at: https://github.com/laravel/laravel/pull/5505/files, currently this line: https://github.com/laravel-frontend-presets/tailwindcss/blob/4f821e72ff7a46057d815d450ce8f7c64f7abe7a/src/TailwindCssPreset.php#L34 is pushing it back to `^5.0.1` a quick fix is to change the `laravel-mix` dependency to `^6.0.6` and run a `npm update`.

**Comment by abubaker417** [comment]
'mix' is not recognized as an internal or external command,

```
$ npm run dev

> @ dev E:\wamp64\www\Laravel8Projects\Laravel_Livewire_JetStream_Projects\jetstream_blog
> npm run development


> @ development E:\wamp64\www\Laravel8Projects\Laravel_Livewire_JetStream_Projects\jetstream_blog
> mix

'mix' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2021-01-18T16_22_38_439Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2021-01-18T16_22_38_470Z-debug.log
```

**Comment by sutcliffe121** [comment]
I also have the same issue. Has anyone managed to get past this? If so, how?

**Comment by sutcliffe121** [comment]
Not sure why it happened but running the following solved my issue:

rm -rf node_modules && npm install && npm run dev

**Comment by dharmatalea** [comment]
I also have the same issue. For fix this chenge `laravel-mix` version `'laravel-mix' => '^5.0.1',` to `'laravel-mix' => '^6.0.6',` and run `npm update`.

**Comment by michaeldyrynda** [comment]
This will be fixed once #128 is merged.

**Comment by Mister-Liro** [comment]
> I also have the same issue. For fix this chenge `laravel-mix` version `'laravel-mix' => '^5.0.1',` to `'laravel-mix' => '^6.0.6',` and run `npm update`.

Did this work for you ?

**Comment by HashTwentyOne** [comment]
it will happen when your cache hold previous files. clear the cache and install the npm again
npm cache clean --force 
then:
   npm install
   npm fix audit
then:
npm run development

**Comment by rainercarr** [comment]
@HashTwentyOne that should be 'npm audit fix'. 

Also, this doesn't work for me, but might work for some people.

What worked for me (on Windows), Laravel was changing "laravel-mix" in "devDependencies" in package-lock.json from "^5.0.1" to "^6.0.6".

**Comment by said0561** [comment]
How do you achieve to to so?

**Comment by Maxlego08** [comment]
> > I also have the same issue. For fix this chenge `laravel-mix` version `'laravel-mix' => '^5.0.1',` to `'laravel-mix' => '^6.0.6',` and run `npm update`.
> 
> Did this work for you ?

This work for me ! Thanks <3

**Comment by said0561** [comment]
Yeah, it works for me, thanks.

**Comment by kojoYeboah53i** [comment]
sometimes it's not just the mix-version. You could clear out your package.json and install only laravel-mix to help u troubleshoot

**Comment by said0561** [comment]
Thanks, I'll check it out.

Mnamo Jumapili, Jul 4, 2021 12:29 Isaac Kojo Yeboah <
***@***.***> aliandika:

**Comment by leonardbos** [comment]
> I also have the same issue. For fix this chenge `laravel-mix` version `'laravel-mix' => '^5.0.1',` to `'laravel-mix' => '^6.0.6',` and run `npm update`.

This worked for me! Thanks.

**Comment by kaangmus** [comment]
work for me : laravel-mix should be updated, I ran `npm install laravel-mix@latest`
