### ISSUE TITLE
Do you have new version of this for laravel 8

### ISSUE THREAD

**Issue by dreadlord12318** [michaeldyrynda/laravel-preset-tailwind#131]
I am using a laravel 8 framework now and it works well without the authentication but with the auth it has the error of login controller not found. Is this a compatibility issue for laravel 8?

**Comment by michaeldyrynda** [comment]
It's not been updated since the release of Laravel 8 and the introduction of [Jetstream](https://jetstream.laravel.com/) and [Breeze](https://laravel.com/docs/8.x/starter-kits#laravel-breeze). Best to use those as a Tailwind starting point if that's what you're after.
