### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by xndbogdan** [michaeldyrynda/laravel-preset-tailwind#134]
I made a PR for fixing laravel 9 compatibility.
https://github.com/laravel-frontend-presets/tailwindcss/pull/133

**Comment by TFWIsaac** [comment]
Still Waiting for this...

I hope it will come soon.

**Comment by mikev032** [comment]
Waiting for this!

**Comment by xndbogdan** [comment]
Released as independent package.
Cheers!
https://packagist.org/packages/xndbogdan/tailwindcss
