### ISSUE TITLE
Compatibility issue with Laravel 10+

### ISSUE THREAD

**Issue by ebnibrahem** [michaeldyrynda/laravel-preset-tailwind#136]
Problem 1
    - laravel-frontend-presets/tailwindcss[0.1.0, ..., 0.4.2] require laravel/framework 5.5.* -> found laravel/framework[v5.5.0, ..., v5.5.50] but it conflicts with your root composer.json require (^10.0).
    - laravel-frontend-presets/tailwindcss 0.4.3 requires laravel/framework 5.5.*|5.6.* -> found laravel/framework[v5.5.0, ..., v5.6.40] but it conflicts with your root composer.json require (^10.0).
    - laravel-frontend-presets/tailwindcss[0.5.0, ..., 0.7.1, 1.0.0, ..., 1.0.3] require laravel/framework ^5.5 -> found laravel/framework[v5.5.0, ..., v5.8.38] but it conflicts with your root composer.json require (^10.0).
    - laravel-frontend-presets/tailwindcss[2.0.0, ..., 2.2.2, 3.0.0] require laravel/framework ^5.5 || ^6.0 -> found laravel/framework[v5.5.0, ..., v5.8.38, v6.0.0, ..., v6.20.44] but it conflicts with your root composer.json require (^10.0).

**Comment by michaeldyrynda** [comment]
This package hasn't been update in some time, either for recent Laravel or Tailwind versions. 

Better to use Laravel's first-party [starter kits](https://laravel.com/docs/10.x/starter-kits), which provide more complete scaffolding and Tailwind support out of the box. 

Alternatively, feel free to submit a PR for 10.x support. I'm time constrained at the moment.
