### ISSUE TITLE
Larval 5.6

### ISSUE THREAD

**Issue by ekrist1** [michaeldyrynda/laravel-preset-tailwind#17]
Is there any plans to support Laravel 5.6?

**Comment by OwenMelbz** [comment]
@ekrist1 By the looks of it it does? https://github.com/laravel-frontend-presets/tailwindcss/blob/master/composer.json

**Comment by michaeldyrynda** [comment]
It didn't when @ekrist1 opened the issue, though I forgot to close it when I added the support.

Let me know if there's still issues, though!
