### ISSUE TITLE
Update the pagination default view to use tailwindcss also.

### ISSUE THREAD

**Issue by wilburpowery** [michaeldyrynda/laravel-preset-tailwind#19]
What about the idea of publishing the pagination views and changing the default.blade.php view to use tailwindcss utilities? 
You can surely do it manually, but it would be really nice to have it done by default when running the preset command.
I can submit a PR with it.

**Comment by wilburpowery** [comment]
I can submit a PR with it.

**Comment by michaeldyrynda** [comment]
I'd leave it out if only to remain consistent with the other presets, but, if you were to include the views, i would a) override the default ones that Laravel publishes to `resources/views/vendor/pagination` and b) offer them as a separate publish tag i.e. `--tag=tailwind-pagination`
