### ISSUE TITLE
Tailwind CSS @apply doesn't work when using preset default

### ISSUE THREAD

**Issue by zachleigh** [michaeldyrynda/laravel-preset-tailwind#3]
See this issue in the Tailwind repo: https://github.com/tailwindcss/tailwindcss/issues/53

The advice in that issue from @adamwathan is sound and corrects the issue. He offers two solutions, they both seem to work but I'm not sure which one would be best for the preset default.

**Comment by michaeldyrynda** [comment]
It's a tricky one, because that issue only really crops up if you're using the `@apply` helper. If you're just using the classes as-is, you won't run into the issue.

I don't think a preset necessarily needs to account for the edge case, seeing as it's one you'll hit whether you use it or not.

**Comment by zachleigh** [comment]
> I don't think a preset necessarily needs to account for the edge case, seeing as it's one you'll hit whether you use it or not.

Good point. Closing this issue.

**Comment by adamwathan** [comment]
If anything maybe just update the CSS stub to match the changes we've made in the docs?

https://tailwindcss.com/docs/installation/#3-use-tailwind-in-your-css
