### ISSUE TITLE
laravel-mix ^2.1 causes error on npm run dev

### ISSUE THREAD

**Issue by davidjr82** [michaeldyrynda/laravel-preset-tailwind#38]
After installing this package following the instructions in readme, the file package.json has updated "laravel-mix": "^2.0" to "laravel-mix": "^2.1", Doing this, the npm run dev fails with the following error description:

`
node_modules/laravel-mix/src/Dependencies.js:41
            process.exit();
                    ^
TypeError: process.exit is not a function
`

After reseting it to 2.0, it works again.

**Comment by michaeldyrynda** [comment]
Just tried and able to replicate, but I believe this error is related to Mix actually installing the Tailwind dependency. Running `npm run dev` again does build out the scaffolding correctly.

May be worth referring it to the Mix repo and seeing if there's issues there?

**Comment by davidjr82** [comment]
The point is that this package changes the require section in package.json. 

Probably we should open an issue in mix repo, but in my opinion the issue in this package is that it shouldn't update the mix dependency if it works fine with the default mix version of a fresh Laravel 5.7 installation (may be I am wrong and in fact this package indeed needs the 2.1 of mix package and I didn't see it yet ..)

**Comment by michaeldyrynda** [comment]
`laravel-mix-purgecss` requires `laravel-mix` 2.1. Everything works, the exit is just a little less than graceful. If you can pinpoint a specific reason, do submit a PR!

**Comment by davidjr82** [comment]
Ok, then I am going to close this issue. Thanks!
