### ISSUE TITLE
Typo in main.css

### ISSUE THREAD

**Issue by ovvessem** [michaeldyrynda/laravel-preset-tailwind#5]
Small typo in main.css

```
* @import "utilities/backgrond-patterns";
```

Change to below to conform to the instructions on https://tailwindcss.com/docs/installation#3-use-tailwind-in-your-css

```
* @import "utilities/background-patterns";
```

**Comment by OwenMelbz** [comment]
Hey @ovvessem are you in a position where you could submit a PR for this yourself? Is always good when people collaborate

**Comment by ovvessem** [comment]
For everything there is a first time: PR submitted (I think :))
