### ISSUE TITLE
App name on navbar should be margin-left not right

### ISSUE THREAD

**Issue by mehrancodes** [michaeldyrynda/laravel-preset-tailwind#53]
I'm not sure why margin has been set to right for [this line](https://github.com/laravel-frontend-presets/tailwindcss/blob/master/src/tailwindcss-stubs/resources/views/layouts/app.blade.php#L20), since every time I have to change it to `ml-6` to show it properly on small screens.

**Comment by michaeldyrynda** [comment]
Happy to accept a PR with this change.

**Comment by mehrancodes** [comment]
@michaeldyrynda seems that there was no problem with the previews mr-6, but since my template was for both LTR/RTL directions, I thought that it should be ml-6 bor both dirs.

So expect my apologies and roll-back, please.
