### ISSUE TITLE
Deleted Bootstrap?

### ISSUE THREAD

**Issue by SturmB** [michaeldyrynda/laravel-preset-tailwind#58]
Setting aside the fact that one should probably not use both Bootstrap and Tailwind at the same time, I have to ask if this preset installer is deleting Bootstrap.

After installing this preset and seeing that it completely destroys my Sass structure, I tried reverting to a commit just before installing this. Doing so, however, now shows this in my main `app.scss` file:

![image](https://user-images.githubusercontent.com/6216224/63295487-c5281000-c29a-11e9-900d-7d82c0e64195.png)

I don't know how to fix this. I don't know what happened at all. Is this preset just assuming that users of it wouldn't also want to use Bootstrap and just deletes it or something? How can I get it back so that this code works again?

**Comment by Nathanw** [comment]
Yeah as you can see from this file: https://github.com/laravel-frontend-presets/tailwindcss/blob/master/src/TailwindCssPreset.php#L29 it will remove bootstrap from `package.json` but you can easily add it back if needed. If you have already reverted the commit you should be able to run `npm install && npm run dev` to re-download the package.

**Comment by SturmB** [comment]
Thank you for clarifying, @Nathanw. My project is back to working condition again, thanks. 🙂

**Comment by michaeldyrynda** [comment]
Yep, the preset is built and installed under the assumption you're adding it to a fresh project, not trying to tack it on to an existing app.
