### ISSUE TITLE
Laravel 6.0 Resent Verification Email

### ISSUE THREAD

**Issue by mikemand** [michaeldyrynda/laravel-preset-tailwind#60]
In Laravel 6.0, the resend verification email route was changed from GET to POST, so now we need to use a form to request another verification email. We could do something similar to the logout link: https://github.com/laravel-frontend-presets/tailwindcss/blob/c37efad9a6bec76ca4ee910b78785f6f862d4f2f/src/tailwindcss-stubs/resources/views/layouts/app.blade.php#L34-L40

**Comment by michaeldyrynda** [comment]
I've opened a PR for this change, do you want to check it out @mikemand ?

**Comment by mikemand** [comment]
I will leave my comments there. Thanks, @michaeldyrynda!
