### ISSUE TITLE
Usage with Laravel 6

### ISSUE THREAD

**Issue by okaufmann** [michaeldyrynda/laravel-preset-tailwind#62]
Hi

What are the plans to make this usable with laravel 6?
Can we just update the composer version reqs to laravel 6?

laravel/ui does not yet has a tailwind preset.

**Comment by okaufmann** [comment]
Okey Okey, for now `composer require laravel-frontend-presets/tailwindcss:dev-master --dev` will do the trick.

A new release containing the latest PRs will fix this.

**Comment by AndrewFeeney** [comment]
@okaufmann Thanks for the workaround!

I also think you should re-open this until the new release is tagged, is it hasn't technically been resolved, at least in my opinion.

**Comment by michaeldyrynda** [comment]
Resolved by #59
