### ISSUE TITLE
Upgrade to Tailwind 1.2.0

### ISSUE THREAD

**Issue by shadracnicholas** [michaeldyrynda/laravel-preset-tailwind#85]
Upgrade tailwind to latest version.

**Comment by krisnaw** [comment]
How? Any update about this?

**Comment by michaeldyrynda** [comment]
We're using `^1.0`, which will install 1.2 for you.

![image](https://user-images.githubusercontent.com/558441/75970256-fc50cc80-5f1f-11ea-872b-eb2fe14ccb5b.png)
