### ISSUE TITLE
Usage for Laravel 6

### ISSUE THREAD

**Issue by ronssij** [michaeldyrynda/laravel-preset-tailwind#96]
I cant use the preset for Laravel 6

> composer require laravel/ui:^1.0 --dev

> composer require laravel-frontend-presets/tailwindcss --dev

**Comment by michaeldyrynda** [comment]
You’ll want to use `^3.0` for Laravel 6.x

**Comment by ronssij** [comment]
You mean the version of the preset? I'll use `^3.0`?

**Comment by ronssij** [comment]
I got it now. Thank you 👍
